on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy initial pages to'     
        required: true
        default: 'gh-pages' 
        type: choice
        options:
        - gh-pages
  repository_dispatch:
    types: [created]

jobs:
  create-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout New Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_FROM: ${{ github.event.inputs.branch }}
        run: |
          BRANCH_FROM=${BRANCH_FROM:-gh-pages}
          printf "GitHub Actor: ${GITHUB_ACTOR}\n"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git branch
          git checkout -b "${BRANCH_FROM}" || git checkout "${BRANCH_FROM}"
          git branch
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          # Move everything from docs into PWD
          cp -R docs/* .
          git add .
          if git diff-index --quiet HEAD --; then
             printf "No changes\n"
          else
             printf "Changes\n"
             git commit -m "Automated deployment of pages! $(date '+%Y-%m-%d')"
             git push origin "${BRANCH_FROM}"
          fi
