name: Update GitHub Pages

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy initial pages to (must be gh-pages)'     
        required: true
        default: 'gh-pages' 
        type: choice
        options:
        - gh-pages
  repository_dispatch:
    types: [created]

jobs:
  create-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Update Website
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: /bin/bash .github/scripts/update_pages.sh
